<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23181" started-at="2022-08-23T12:10:54Z" finished-at="2022-08-23T12:11:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23181" started-at="2022-08-23T12:10:54Z" finished-at="2022-08-23T12:11:17Z">
      <class name="Practice.Topic03_Browser_Command">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="beforeClass" is-config="true" duration-ms="3531" started-at="2022-08-23T19:10:54Z" finished-at="2022-08-23T19:10:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC01_Verify_URL()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="TC01_Verify_URL" duration-ms="7171" started-at="2022-08-23T19:10:58Z" finished-at="2022-08-23T19:11:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Verify_URL -->
        <test-method status="PASS" signature="TC02_Verify_Title()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="TC02_Verify_Title" duration-ms="4726" started-at="2022-08-23T19:11:05Z" finished-at="2022-08-23T19:11:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_Verify_Title -->
        <test-method status="PASS" signature="TC03_Navigate_Function()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="TC03_Navigate_Function" duration-ms="6006" started-at="2022-08-23T19:11:10Z" finished-at="2022-08-23T19:11:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_Navigate_Function -->
        <test-method status="FAIL" signature="TC04_Get_PageSource()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="TC04_Get_PageSource" duration-ms="1258" started-at="2022-08-23T19:11:16Z" finished-at="2022-08-23T19:11:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Practice.Topic03_Browser_Command.TC04_Get_PageSource(Topic03_Browser_Command.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_Get_PageSource -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Practice.Topic03_Browser_Command@48eff760]" name="afterClass" is-config="true" duration-ms="467" started-at="2022-08-23T19:11:17Z" finished-at="2022-08-23T19:11:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Practice.Topic03_Browser_Command -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
